server:
  port: 8090

spring:
  datasource:
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: epamtestsystem@gmail.com
    password: password12345
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
gitlab:
  private_token: xNNi8mBG_rxUJxsUehUt

vk:
  group:
    id: 150227212
    access_token: 53f3aad05d484220277c72413807c33b88846e35ca2585079d572a6ad064fc0d2a0b875a5646ced937258