spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gitTestSystemTest?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false